[subtitle-generator-auth]
enabled  = true
port     = 443,80
filter   = subtitle-generator
logpath  = /opt/subtitle-generator/logs/app.log
maxretry = 20
findtime = 60
bantime  = 3600

[subtitle-generator-http]
enabled  = true
port     = 443,80
filter   = subtitle-generator
logpath  = /opt/subtitle-generator/logs/app.log
maxretry = 100
findtime = 60
bantime  = 600
