"""Phase Lumen L64 — Advanced rate limiting middleware tests.

Tests exempt paths, key isolation, rate limit headers on success,
and allowlist bypass behavior.
-- Shield (Security Engineer)
"""

from fastapi.testclient import TestClient

from app.main import app
from app.services.rate_limiter import (
    _buckets,
    add_to_allowlist,
    check_rate_limit,
    get_rate_limit_headers,
    remove_from_allowlist,
)

client = TestClient(app, base_url="https://testserver")


# ======================================================================
# RATE LIMIT EXEMPT PATHS
# ======================================================================


class TestRateLimitExemptPaths:
    """Test paths exempt from rate limiting."""

    def test_api_status_never_triggers_429(self):
        """GET /api/status never triggers 429 even with heavy traffic."""
        for _ in range(80):
            res = client.get("/api/status")
            assert res.status_code != 429

    def test_health_stream_is_exempt_path(self):
        """health/stream is in the exempt paths set."""
        from app.middleware.rate_limit import _EXEMPT_PATHS

        assert "/health/stream" in _EXEMPT_PATHS

    def test_health_endpoint_exempt(self):
        """GET /health is exempt from rate limiting."""
        for _ in range(80):
            res = client.get("/health")
            assert res.status_code != 429

    def test_health_live_exempt(self):
        """GET /health/live is exempt from rate limiting."""
        for _ in range(80):
            res = client.get("/health/live")
            assert res.status_code != 429

    def test_metrics_exempt(self):
        """GET /metrics is exempt from rate limiting."""
        for _ in range(80):
            res = client.get("/metrics")
            assert res.status_code != 429


# ======================================================================
# RATE LIMIT KEY ISOLATION
# ======================================================================


class TestRateLimitKeyIsolation:
    """Test that upload and general rate limit buckets are isolated."""

    def test_upload_exhaustion_does_not_affect_general(self):
        """Exhausting upload requests doesn't affect general IP bucket."""
        upload_key = "upload:testclient"
        general_key = "ip:testclient"
        try:
            for _ in range(10):
                check_rate_limit(upload_key, limit=5, window=60)
            allowed, info = check_rate_limit(general_key, limit=60, window=60)
            assert allowed is True
        finally:
            _buckets.pop(upload_key, None)
            _buckets.pop(general_key, None)

    def test_general_exhaustion_does_not_affect_upload(self):
        """Exhausting general bucket doesn't affect upload bucket."""
        upload_key = "upload:keyiso2"
        general_key = "ip:keyiso2"
        try:
            for _ in range(65):
                check_rate_limit(general_key, limit=60, window=60)
            allowed, info = check_rate_limit(upload_key, limit=5, window=60)
            assert allowed is True
        finally:
            _buckets.pop(upload_key, None)
            _buckets.pop(general_key, None)

    def test_different_ips_have_separate_buckets(self):
        """Different IP addresses use separate rate limit buckets."""
        key1 = "ip:10.0.0.1"
        key2 = "ip:10.0.0.2"
        try:
            for _ in range(65):
                check_rate_limit(key1, limit=60, window=60)
            allowed, _ = check_rate_limit(key2, limit=60, window=60)
            assert allowed is True
        finally:
            _buckets.pop(key1, None)
            _buckets.pop(key2, None)


# ======================================================================
# RATE LIMIT HEADERS ON SUCCESS
# ======================================================================


class TestRateLimitHeadersOnSuccess:
    """Test rate limit headers generated by the rate limiter service."""

    def test_success_info_produces_limit_header(self):
        """get_rate_limit_headers includes X-RateLimit-Limit for allowed requests."""
        key = "test_header_limit"
        try:
            _, info = check_rate_limit(key, limit=60, window=60)
            headers = get_rate_limit_headers(info)
            assert "X-RateLimit-Limit" in headers
            assert headers["X-RateLimit-Limit"] == "60"
        finally:
            _buckets.pop(key, None)

    def test_success_info_produces_remaining_header(self):
        """get_rate_limit_headers includes X-RateLimit-Remaining."""
        key = "test_header_remaining"
        try:
            _, info = check_rate_limit(key, limit=60, window=60)
            headers = get_rate_limit_headers(info)
            assert "X-RateLimit-Remaining" in headers
            assert int(headers["X-RateLimit-Remaining"]) == 59
        finally:
            _buckets.pop(key, None)

    def test_remaining_decrements_on_successive_requests(self):
        """Remaining value decrements on successive check_rate_limit calls."""
        key = "test_header_decrement"
        try:
            _, info1 = check_rate_limit(key, limit=60, window=60)
            _, info2 = check_rate_limit(key, limit=60, window=60)
            h1 = get_rate_limit_headers(info1)
            h2 = get_rate_limit_headers(info2)
            assert int(h2["X-RateLimit-Remaining"]) < int(h1["X-RateLimit-Remaining"])
        finally:
            _buckets.pop(key, None)

    def test_limit_header_reflects_configured_value(self):
        """X-RateLimit-Limit reflects the configured limit value."""
        key = "test_header_configured"
        try:
            _, info = check_rate_limit(key, limit=100, window=60)
            headers = get_rate_limit_headers(info)
            assert headers["X-RateLimit-Limit"] == "100"
        finally:
            _buckets.pop(key, None)


# ======================================================================
# RATE LIMIT ALLOWLIST BYPASS
# ======================================================================


class TestRateLimitAllowlistBypass:
    """Test that allowlisted IPs bypass rate limiting entirely."""

    def test_allowlisted_ip_bypasses_rate_limit(self):
        """Allowlisted IP with exhausted bucket still gets 200."""
        ip = "10.99.99.99"
        key = f"ip:{ip}"
        try:
            add_to_allowlist(ip)
            for _ in range(65):
                check_rate_limit(key, limit=60, window=60)
            from app.services.rate_limiter import is_ip_allowed

            assert is_ip_allowed(ip) is True
        finally:
            remove_from_allowlist(ip)
            _buckets.pop(key, None)

    def test_non_allowlisted_ip_not_bypassed(self):
        """Non-allowlisted IP is subject to rate limiting."""
        from app.services.rate_limiter import is_ip_allowed

        assert is_ip_allowed("10.99.99.100") is None
